### ISSUE TITLE
Certain vehicles seem to be breaking...

### ISSUE THREAD

**Issue by originalfoo** [joaofarias/csl-traffic#40] opened 2015-05-27 09:14 UTC
The "Insect" vans (I assume the ones with the bug spray advert on the side) - seen two or three reports similar to this:

.1. http://www.reddit.com/r/CitiesSkylines/comments/37flpv/insect_cars_doent_move_at_all/

Hot dog vans and tractors too:

.2. http://www.reddit.com/r/CitiesSkylines/comments/37e4jm/release_traffic_bus_bonanza/crmawjf

Box trucks:

.3. http://steamcommunity.com/workshop/filedetails/discussion/409184143/613958868376457349/#c615085406651944827

Maybe something to do with realistic vehicle speeds option....

.4. http://steamcommunity.com/workshop/filedetails/discussion/409184143/613958868376457349/#c615085406651982221

**Comment by originalfoo** [comment] 2015-05-27 09:15
If it is the realistic speeds then prolly need to do a check to see that updated speed hasn't resulted in vehicle having no speed?

**Comment by joaofarias** [comment] 2015-05-27 09:36
It's not the realistic speeds - I haven't touched it.
I have changed the way I replace the AI, but if something went wrong they would have the default behavior (ignoring lane restrictions), not stopping completely.

And then there's people saying that ghost mode doesn't fix it, so it can't be my path finder. Ask for logs, please.

**Comment by originalfoo** [comment] 2015-05-27 09:39
Another one:

.5. http://steamcommunity.com/workshop/filedetails/discussion/409184143/613958868376457349/?tscn=1432718915#c615085406650784387

**Comment by joaofarias** [comment] 2015-05-27 09:40
I answered that already.

**Comment by originalfoo** [comment] 2015-05-27 13:01
Another one: 

.6. http://www.reddit.com/r/CitiesSkylines/comments/37e4jm/release_traffic_bus_bonanza/crmelwo?context=3

**Comment by originalfoo** [comment] 2015-05-27 13:53
Another person stating that turning off realistic speeds solved it for them:

relates to report .6. http://www.reddit.com/r/CitiesSkylines/comments/37e4jm/release_traffic_bus_bonanza/crmgcvh?context=3

Maybe realistic speeds isn't directly the problem, but just makes problem manifest sooner? Specifically, it leads to more traffic on roads, and what happens if the game engine can't process all traffic in sufficient time? Is there a point where it will skip vehicles?

**Comment by originalfoo** [comment] 2015-05-27 14:42
A log file posted by a reddit user relating to this issue:

relates to report .6. http://pastebin.com/ihcBU7aK

**Comment by joaofarias** [comment] 2015-05-27 18:50
I cannot reproduce this issue and the logs we've received don't show anything. Can you please ask people to show a screenshot of the stopped vehicles?
I'll work on the button disabling other tools bug.

**Comment by originalfoo** [comment] 2015-05-27 19:48
The only time I've had traffic stall is if there's a metro under a road near a junction (most likely copy and paste code in metro AI from Train AI or something?) - I've not had vehicles stopping mid road.

Will ask for screenshots, etc.

**Comment by originalfoo** [comment] 2015-05-27 20:10
Possibly another one, although could be caused by game's subway bug (will monitor):

.7. http://steamcommunity.com/app/255710/discussions/0/615085406653709796/

**Comment by originalfoo** [comment] 2015-05-27 20:26
Possibly another one (investigating):

.8. http://www.reddit.com/r/CitiesSkylines/comments/37hy2q/anyone_knows_how_is_this_possible_stucked_truck/

**Comment by originalfoo** [comment] 2015-05-27 20:56
Collating information for report .1. (Odatas on reddit)

Source: http://www.reddit.com/r/CitiesSkylines/comments/37flpv/insect_cars_doent_move_at_all/

Affects: Vans

Plugins:
- [x] Automatic Bulldoze
- [x] Commercial Demand Fix
- [ ] Traffic Report Tool
- [ ] Auto Line Color
- [x] Automatic Emptying
- [ ] Enable Achievements
- [x] Western Siren Mod
- [x] Transport Capacity
- [ ] Toggle Traffic Lights
- [x] Unlock Basic Roads
- [x] Infinite Oil And Ore
- [ ] Extended Public Transport UI
- [x] Ambient Occlusion
- [ ] Aris Skyline overwatch (With Garbage Truck AI and Hearse AI)
- [ ] Traffic ++
- [ ] Precision Engineering

**Comment by originalfoo** [comment] 2015-05-27 21:05
Collating information for report .2. (Interurban_Era on reddit)

Source: http://www.reddit.com/r/CitiesSkylines/comments/37e4jm/release_traffic_bus_bonanza/crmawjf

Affected: Hotdog trucks, Farm tractors w/ trailer

no further info yet

**Comment by originalfoo** [comment] 2015-05-27 21:05
Collating information for report .3.

Source: http://steamcommunity.com/workshop/filedetails/discussion/409184143/613958868376457349/#c615085406651944827

Affects: Box trucks

RESOLVED: Turned off realistic vehicle speeds. (He noted that turning option back on afterwards did not recreate the error - unlike some other reports listed)

Log file: http://pastebin.com/f4ksbnJy

**Comment by originalfoo** [comment] 2015-05-27 21:05
Collating information for report .4. (Imperial Guardsmen on steam)

Source: http://steamcommunity.com/workshop/filedetails/discussion/409184143/613958868376457349/#c615085406651982221

Affects: Donut trucks, Box trucks, Fire engines, Ore trucks

RESOLVED: Disable realistic speeds, then restart the app. (Did not work if app started with that option enabled, also once option is enabled the problem returns)
- [ ] Unlock All
- [x] 25 spaces
- [x] First person camera
- [x] Simcity Fudged Population
- [ ] Pollution Color Changer
- [x] 1/4 Citizen Aging Speed
- [x] Ambient Occlusion
- [ ] Sun Shafts
- [x] Infinite oil and ore
- [x] Auto Bulldoze
- [ ] Extended Public Transport UI
- [ ] Control Building Level Up
- [x] Tsunami Disaster
- [ ] Traffic Report Tool
- [ ] Extended Building Info
- [x] Fine Road Heights
- [x] Area Enabler
- [ ] Terraform Tool
- [ ] ARIS hearse, garbage, remove stuck vehicle, early death mods
- [ ] Road Color Changer
- [ ] Toggle Traffic Lights

**Comment by originalfoo** [comment] 2015-05-27 21:06
Collating information for report .5. (cgrazko on steam)

Source: http://steamcommunity.com/workshop/filedetails/discussion/409184143/613958868376457349/?tscn=1432718915#c615085406650784387

Affects: Donut trucks

no further info yet

**Comment by originalfoo** [comment] 2015-05-27 21:14
Collating information for report .6. (gaijin5 on reddit)

RESOLVED: Turned off realistic speeds option and vehicles started working again.

Log file: http://pastebin.com/ihcBU7aK

Plugins:
- [ ] Extended Road Upgrade
- [ ] Precision Engineering
- [x] Traffic Manager
- [x] First Person Camera
- [x] Automatic Bulldoze
- [x] Automatic Emptying
- [ ] Tree Brush
- [ ] Traffic++

T++ Options:
- [ ] Enhanced AI
- [ ] Prevent Vehicle Despawn
- [x] Realistic Speeds

**Comment by originalfoo** [comment] 2015-05-27 21:24
Collating information for report .7. (Bender on steam)

Source: http://steamcommunity.com/app/255710/discussions/0/615085406653709796/

Affects: Lorries (Box trucks?)

Screenshot: http://tinypic.com/view.php?pic=59yj41&s=8

![59yj41](https://cloud.githubusercontent.com/assets/1386719/7848042/33b34cc6-04c0-11e5-9e95-cce6dfa719e5.png)

**Comment by originalfoo** [comment] 2015-05-27 21:27
Collating information for report .8. (Figazza1 on reddit)

Source: http://www.reddit.com/r/CitiesSkylines/comments/37hy2q/anyone_knows_how_is_this_possible_stucked_truck/

Affects: White trucks

Screenshot: http://imgur.com/1nM7zik

![1nm7zik](https://cloud.githubusercontent.com/assets/1386719/7848323/a3c3124c-04c2-11e5-9bb9-74ec1e42b5ec.jpg)

Disabling entire T++ mod had no effect.
- [ ] Traffic++
- [x] Traffic Manager
- [x] Automatic Bulldoze
- [ ] Dynamic Resolution
- [x] Multi Track Station Enabler
- [x] All 25 Areas Purchaseable

**Comment by originalfoo** [comment] 2015-05-27 21:55
Collating information for report .9. (Froggypwns on reddit)

Source: http://www.reddit.com/r/CitiesSkylines/comments/37e4jm/release_traffic_bus_bonanza/crmgc3p

Affected: Garbage trucks

RESOLVED: Disabled realistic vehicle speeds

**Comment by originalfoo** [comment] 2015-05-27 22:10
OK, just a stab in the dark here - we've not had any reports of it affecting civilian transport (cars, mopeds), police cars, hearses, ambulances.

What's the common theme between everything else (fire truck, cargo trucks - all sizes, garbage trucks)? Could it be the "heavy vehicle" flag?

**Comment by joaofarias** [comment] 2015-05-27 22:20
Sorry, I have been working with a guy that is running some tests for me and I think I found the problem. I'm just finishing a new version for him to test so I'll let you know how it went in a few.

**Comment by joaofarias** [comment] 2015-05-27 22:44
Ok, I was able to fix it.
It was due to the changes I made on how vehicle AIs are replaced. Basically, the variable that controls the realistic speeds wasn't intialized now, so it had a speed multiplier of 0. Why it didn't affect all vehicles is just proof of how much I don't know about the game's code :/

**Comment by originalfoo** [comment] 2015-05-27 22:52
I bet that will also solve some vehicles not respecting speed limit customisations as well!

**Comment by joaofarias** [comment] 2015-05-28 01:16
Maybe.. I really don't know :/

I've released the hotfix so this is now fixed. Thanks for keeping track of bug reports on reddit. :)

**Closed as completed by joaofarias** 2015-05-28 01:16 UTC

**Comment by originalfoo** [comment] 2015-05-28 01:34
I've replied to them all personally to let them know a new release is out fixing the bug they reported a few hours ago. :)
